#############################################################################
#                      GIT-ENFORCER RULE FILE GUIDELINES
#############################################################################
#
# This is a sample YML file for structuring your PR mergability requirements and
# issues that are created within your repository or organization.
#
# Any any time you want to ignore a particular rule, comment it out or don't add
# it into the file.
#
# ------------------------------------------------------------------------
# BELOW IS THE LIST OF AVAILABLE RULE DEFINITIONS THAT CAN BE DEFINED:
# ------------------------------------------------------------------------
# approvals: Any integer value that represents the no. of required approvers.
# title_must_contain: Regex rule that needs to contain string, pipe delimiter
# title_must_not_contain: Regex rule that must not contain string, pipe delimiter
# title_must_be_prefixed: Prefix requirement for PR title
# title_must_be_suffixed: Suffix requirement for PR title
# commit_must_be_prefixed: Prefix requirement for PR (individual commits)
# commit_must_be_suffixed: Suffix requirement for PR (individual commits)
# validate_label_population: Ensures that labels must be added to an opened issue
#############################################################################

# Here is an example git-enforcer policy. A more detailed policy guide can be
# found within the GitHub readme.
git-enforcer:
  labels:
    add_label_on_failure:
      color: "FFA500"
      name: "Issue Failure"
    title_must_contain:
      pattern: null
    title_must_not_contain:
      pattern: null
    title_must_be_prefixed:
      prefix: "[GIT-ENFORCE]"
    title_must_be_suffixed:
      suffix: SUFFIX
    validate_label_population:
      message: "Don't create issues with no labels!"
    validate_assignee_population:
      message: "Remember to choose at least one assignee to this issue!"
    milestone_required:
      message: "A milestone is required to be selected when making a new issue"
      required_milestone_name: null
  pull_requests:
    approvals:
      number: 0
    title_must_contain:
      pattern: null
    title_must_not_contain:
      pattern: null
    title_must_be_prefixed:
      prefix: null
      suffix: null
    commits_must_be_prefixed:
      prefix: null
    commits_must_be_suffixed:
      suffix: null
