#############################################################################
#                      GIT-ENFORCER RULE FILE GUIDELINES
#############################################################################
#
# This is a sample YML file for structuring your PR mergability requirements
# Any any time you want to ignore a particular rule, write null or delete the
# entirely.
#
# approvals: Any integer value that represents the no. of required approvers.
# title_must_contain: Regex rule that needs to contain string, pipe delimiter
# title_must_not_contain: Regex rule that must not contain string, pipe delimiter
# title_must_be_prefixed: Prefix requirement for PR title
# title_must_be_suffixed: Suffix requirement for PR title
# commit_must_be_prefixed: Prefix requirement for PR (individual commits)
# commit_must_be_suffixed: Suffix requirement for PR (individual commits)
# validate_label_population: Ensures that labels must be added to an opened issue
#############################################################################

# Here is an example git-enforcer policy:
# All settings can be saved, but toggling the enabled flag will conditionally
# shut them off 1 by 1.
git-enforcer:
  labels:
    add_label_on_failure:
      enabled: true
      color: "FFA500"
      name: "Issue Failure"
    title_must_contain:
      enabled: true
      pattern: null
    title_must_not_contain:
      enabled: true
      pattern: null
    title_must_be_prefixed:
      enabled: true
      prefix: "[GIT-ENFORCE]"
    title_must_be_suffixed:
      enabled: true
      suffix: SUFFIX
    validate_label_population:
      enabled: true
      message: "Don't create issues with no labels!"
    validate_assignee_population:
      enabled: true
      message: "Remember to choose at least one assignee to this issue!"
    milestone_required:
      enabled: true
      message: "A milestone is required to be selected when making a new issue"
      required_milestone_name: null
    project_required:
      enabled: true
      message: "A project is required to be selected when making a new issue"
      required_project_name: null
  pull_requests:
    approvals:
      enabled: true
      number: 0
    title_must_contain:
      enabled: true
      pattern: null
    title_must_not_contain:
      enabled: true
      pattern: null
    title_must_be_prefixed:
      enabled: true
      prefix: null
    title_must_be_suffixed:
      enabled: true
      suffix: null
    commits_must_be_prefixed:
      enabled: true
      prefix: null
    commits_must_be_suffixed:
      enabled: true
      suffix: null
